version: '3'

services:
  couch:
    image: public.ecr.aws/docker/library/couchdb:3
    environment:
      COUCHDB_USER: futon
      COUCHDB_PASSWORD: futon
    ports:
      - '5984:5984'
    volumes:
      - couch:/opt/couchdb/data

volumes:
  couch: {}
